{{- define "dockerConfig" }}
  auths:
    "ghcr.io":
      username: "{{ required "ghcrlogin.username is required" .Values.ghcrlogin.username }}"
      password: "{{ required "ghcrlogin.password is required" .Values.ghcrlogin.password }}"
      auth: {{ (printf "%s:%s" .Values.ghcrlogin.username .Values.ghcrlogin.password) | b64enc | quote }}
{{- end }}
{{- if .Values.ghcrlogin }}
{{- $dockerConfig := include "dockerConfig" . | fromYaml }}
apiVersion: v1
data:
  .dockerconfigjson: {{ $dockerConfig | toPrettyJson | b64enc | quote }}
kind: Secret
metadata:
  name: {{ .Values.imagePullSecret }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-2"
type: kubernetes.io/dockerconfigjson
{{- end }}