{{- define "dockerConfig" }}
  auths:
    {{ required "dockerlogin.server is required" .Values.dockerlogin.server | quote }}:
      username: "{{ required "dockerlogin.username is required" .Values.dockerlogin.username }}"
      password: "{{ required "dockerlogin.password is required" .Values.dockerlogin.password }}"
      auth: {{ (printf "%s:%s" .Values.dockerlogin.username .Values.dockerlogin.password) | b64enc | quote }}
{{- end }}
{{- if .Values.dockerlogin.username }}
{{- $dockerConfig := include "dockerConfig" . | fromYaml }}
apiVersion: v1
data:
  .dockerconfigjson: {{ $dockerConfig | toPrettyJson | b64enc | quote }}
kind: Secret
metadata:
  name: {{ required "dockerlogin.secretName is required" .Values.dockerlogin.secretName }}
type: kubernetes.io/dockerconfigjson
{{- end }}