apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: {{ printf "%s-stripprefix" .Chart.Name | quote }}
spec:
  stripPrefixRegex:
    regex:
      - "/generic-channel-demo"

---
{{- $mws := list -}}
{{- range $mw := (list "stripprefix") -}}
  {{- $mws = append $mws (printf "%s-%s-%s@kubernetescrd" $.Release.Namespace $.Chart.Name $mw) -}}
{{- end -}}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: "{{ .Chart.Name }}"
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
    traefik.ingress.kubernetes.io/router.tls: "true"
    traefik.ingress.kubernetes.io/router.middlewares: {{ join "," $mws | quote }}
spec:
  rules:
    - host: {{ required "domain is required" .Values.domain | quote }}
      http:
        paths:
          - path: "/generic-channel-demo"
            pathType: Prefix
            backend:
              service:
                name: "{{ .Chart.Name }}"
                port:
                  name: http
