apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mluvii-generic-channel-demo-redis
  labels:
    app: mluvii-generic-channel-demo-redis
spec:
  serviceName: mluvii-generic-channel-demo-redis
  replicas: 1
  selector:
    matchLabels:
      app: mluvii-generic-channel-demo-redis
  template:
    metadata:
      labels:
        app: mluvii-generic-channel-demo-redis
    spec:
      containers:
        - name: redis
          image: "redis:6.2"
          command:
            - redis-server
            - "/etc/redis/redis.conf"
          ports:
            - name: redis
              containerPort: 6379
          volumeMounts:
            - mountPath: /var/lib/redis
              name: data
            - mountPath: /etc/redis
              name: config
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: mluvii-generic-channel-demo-redis-data
        - name: config
          configMap:
            name: mluvii-generic-channel-demo-redis-config
            items:
              - key: redis.conf
                path: redis.conf

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mluvii-generic-channel-demo-redis-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
  storageClassName: do-block-storage

---

apiVersion: v1
kind: Service
metadata:
  name: mluvii-generic-channel-demo-redis
spec:
  selector:
    app: mluvii-generic-channel-demo-redis
  ports:
    - name: redis
      protocol: TCP
      port: 6379
      targetPort: redis

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: mluvii-generic-channel-demo-redis-config
data:
  redis.conf: |
    bind 0.0.0.0
    protected-mode yes
    port 6379
    tcp-backlog 511
    timeout 0
    tcp-keepalive 300
    daemonize no
    supervised no
    pidfile /var/run/redis/redis-server.pid
    loglevel notice
    logfile ""
    databases 16
    always-show-logo yes
    save ""
    stop-writes-on-bgsave-error yes
    rdbcompression yes
    rdbchecksum yes
    dbfilename dump.rdb
    dir /var/lib/redis
    slave-serve-stale-data yes
    slave-read-only yes
    repl-diskless-sync no
    repl-diskless-sync-delay 5
    repl-disable-tcp-nodelay no
    slave-priority 100
    maxmemory 1073741824
    maxmemory-policy allkeys-lru
    lazyfree-lazy-eviction no
    lazyfree-lazy-expire no
    lazyfree-lazy-server-del no
    slave-lazy-flush no
    appendonly yes
    appendfilename "appendonly.aof"
    appendfsync everysec
    no-appendfsync-on-rewrite no
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    aof-load-truncated yes
    aof-use-rdb-preamble no
    lua-time-limit 5000
    slowlog-log-slower-than 10000
    slowlog-max-len 128
    latency-monitor-threshold 0
    notify-keyspace-events Exe
    hash-max-ziplist-entries 512
    hash-max-ziplist-value 64
    list-max-ziplist-size -2
    list-compress-depth 0
    set-max-intset-entries 512
    zset-max-ziplist-entries 128
    zset-max-ziplist-value 64
    hll-sparse-max-bytes 3000
    activerehashing yes
    client-output-buffer-limit normal 0 0 0
    client-output-buffer-limit slave 256mb 64mb 60
    client-output-buffer-limit pubsub 32mb 8mb 60
    hz 10
    aof-rewrite-incremental-fsync yes
