name: Deploy

# https://some-natalie.dev/blog/kubernoodles-pt-4/

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to install on'
        type: environment
        required: true
        default: 'demo'
      release-name:
        description: 'Name of the Helm Release'
        required: true
        default: 'mluvii-generic-channel-demo'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: mluvii
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Write out the kubeconfig info
        run: echo ${{ secrets.KUBECONFIG }} | base64 -d > /tmp/config

      - name: Install or upgrade
        run: |
          HELMCMD=`helm -n ${{ vars.NAMESPACE }} status ${{ inputs.release-name }} >/dev/null 2>&1 && echo upgrade || echo install`
          echo Executing $HELMCMD
          helm -n ${{ vars.NAMESPACE }} $HELMCMD \
          --set domain="${{ vars.DOMAIN }}" \
          --set apiPassword="${{ secrets.API_PASSWORD }}" \
          ${{ inputs.release-name }} "oci://ghcr.io/mluvii/${{ inputs.release-name }}"
        env:
          KUBECONFIG: /tmp/config

      - name: Remove kubeconfig info
        run: rm -f /tmp/config
